class EX:
    """异常常量类"""
    
    # 系统相关
    SYSTEM_NOT_ROUTE_MATCHING = "SYSTEM_NOT_ROUTE_MATCHING"
    
    # API相关
    API_REQUEST_PARAMS_INVALID = "API_REQUEST_PARAMS_INVALID"
    API_FILE_URL_INVALID = "API_FILE_URL_INVALID"
    API_FILE_EXECEEDS_SIZE = "API_FILE_EXECEEDS_SIZE"
    API_REQUEST_FAILED = "API_REQUEST_FAILED"
    API_IMAGE_GENERATION_FAILED = "API_IMAGE_GENERATION_FAILED"
    API_CONTENT_FILTERED = "API_CONTENT_FILTERED"
    
    # 会话相关
    SESSION_TOKEN_EXPIRED = "SESSION_TOKEN_EXPIRED"
    SESSION_TOKEN_INVALID = "SESSION_TOKEN_INVALID"